service: foosball-api

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  user-create:
    handler: bin/foosball-api-user-create
    events:
      - http:
          path: /user
          method: post
    environment:
      POSTGRES_HOST: foosball-com.cixfoebrlww0.us-east-1.rds.amazonaws.com
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: foosballhq_staging
      POSTGRES_USERNAME: foosballadmin